# Downsampling and BIDS conversion

## Introduction

This section outlines how to prepare the data for further analysis. The initial step involves downsampling the data to an appropriate sampling frequency. Following this, the data will be organised according to the MEG Brain Imaging Data Structure (MEG-BIDS) [1]. This ensures that the necessary metadata are available and a consistent file structure are across datasets. During BIDS construction, trigger information will also be derived and labelled.

## Preparation

Import the required modules:

In [1]:
import os
import numpy as np
import pandas as pd
import mne
from mne_bids import (
    BIDSPath,
    make_dataset_description,
    print_dir_tree,
    read_raw_bids,
    write_meg_calibration,
    write_meg_crosstalk,
    write_raw_bids
)

## File overview

The chapter relies on reading the raw FIF-files generated by the acquisition system:
~~~
<ROOT>/20250308_162348_sub-P5EA_file-SubP5EA_raw.fif
~~~ 
the downsampled FIF-files are then generated followed by BIDS data: 
~~~
<ROOT>/20250308_162348_sub-P5EA_file-SubP5EA_raw_fs_raw.fif
<ROOT>/20250308_162348_sub-P5EA_file-SubP5EA_raw_eve.fif

<ROOT/Fieldline_Spatt_BIDS/participants.json
<ROOT/Fieldline_Spatt_BIDS/participants.tsv
<ROOT/Fieldline_Spatt_BIDS/sub-01/ses-01/sub-01_ses-01_scans.tsv
<ROOT/Fieldline_Spatt_BIDS/dataset_description.json
<ROOT/Fieldline_Spatt_BIDS/sub-01/ses-01/meg/sub-01_ses-01_coordsystem.json
<ROOT/Fieldline_Spatt_BIDS/ses-01/meg/sub-01_ses-01_task-SpAtt_run-1_channels.tsv
<ROOT/Fieldline_Spatt_BIDS/ses-01/meg/sub-01_ses-01_task-SpAtt_run-1_events.json
<ROOT/Fieldline_Spatt_BIDS/meg/sub-01_ses-01_task-SpAtt_run-1_events.tsv
<ROOT/Fieldline_Spatt_BIDS/meg/sub-01_ses-01_task-SpAtt_run-1_meg.fif
<ROOT/Fieldline_Spatt_BIDS/sub-01_ses-01_task-SpAtt_run-1_meg.json
~~~

## Downloading and storing the raw data locally
Visit [Zenedo](https://zenodo.org/) and download the dataset. TO BE UPDATED 


## Importing the data

The OPM data are stored in FIF-format, which is a binary file structure with embedded labels. The first step is to import the data by defining the data path for the local data. **THIS IS USER DEPENDENT**. The acquisition systems break the data up across multiple files as the total size of a FIF-file cannot exceed 2Gb; however, MNE Python will automatically handle the different sub-files. 

In [12]:
# The path below is dependent on where the user has stored the data locally

data_path = 'E:/new_fieldline/sub-H'

file_name = '20260604_162421_sub-H_file-subjectHData_raw.fif'

raw_fname = os.path.join(data_path, file_name)
raw_resampled_fname = raw_fname.replace('meg.fif', f'rs_raw.fif')

event_fname = raw_fname.replace('.fif', f'_eve.fif')
bids_folder = os.path.join(data_path, "Fieldline_Spatt_BIDS")

print(raw_fname)
print(event_fname)

E:/new_fieldline/sub-H\20260604_162421_sub-H_file-subjectHData_raw.fif
E:/new_fieldline/sub-H\20260604_162421_sub-H_file-subjectHData_raw_eve.fif


Now read the raw data:

In [3]:
raw = mne.io.read_raw_fif(raw_fname, preload=True)

Opening raw data file E:/new_fieldline/sub-H\20260604_162421_sub-H_file-subjectHData_raw.fif...
    Range : 0 ... 9380499 =      0.000 ...  1876.100 secs
Ready.
Reading 0 ... 9380499  =      0.000 ...  1876.100 secs...


In [4]:
print(raw.info)

<Info | 17 non-empty values
 bads: []
 ch_names: L102_bz-s30, L104_bz-s83, L106_bz-s81, L108_bz-s79, L110_bz-s70, ...
 chs: 71 Magnetometers, 1 Stimulus
 custom_ref_applied: False
 description: {"chassis":{"version":"0.9.4- ...
 dig: 6 items (3 Cardinal, 3 HPI)
 experimenter: KP
 file_id: 4 items (dict)
 gantry_angle: 0.0
 highpass: 0.0 Hz
 line_freq: 0.0
 lowpass: 500.0 Hz
 meas_date: 2026-06-04 15:24:21 UTC
 meas_id: 4 items (dict)
 nchan: 72
 proj_id: 21923
 proj_name: SFLUX
 projs: []
 sfreq: 5000.0 Hz
 xplotter_layout: None
>


## Down Sampling the Raw Data

In [10]:
desired_sfreq = 1000
current_sfreq = raw.info['sfreq']

lowpass_freq = desired_sfreq / 4.0
highpass_freq = 0.1

raw_resampled = raw.copy().filter(l_freq=highpass_freq, h_freq=lowpass_freq)

raw_resampled.resample(sfreq=desired_sfreq)

Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 0.1 - 2.5e+02 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 0.10
- Lower transition bandwidth: 0.10 Hz (-6 dB cutoff frequency: 0.05 Hz)
- Upper passband edge: 250.00 Hz
- Upper transition bandwidth: 62.50 Hz (-6 dB cutoff frequency: 281.25 Hz)
- Filter length: 165001 samples (33.000 s)

Finding events on: di32
Trigger channel di32 has a non-zero initial value of 1024 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
1529 events found on stim channel di32
Event IDs: [    4   256  1024  4096 16384 65536]
Finding events on: di32
Trigger channel di32 has a non-zero initial value of 1024 (consider using initial_event=True to detect this event)
Remov

C:\Users\arakshit\AppData\Local\Temp\ipykernel_37968\1346616213.py:9: RuntimeWarning: Resampling of the stim channels caused event information to become unreliable. Consider finding events on the original data and passing the event matrix as a parameter.
  raw_resampled.resample(sfreq=desired_sfreq)


<Raw | 20260604_162421_sub-H_file-subjectHData_raw.fif, 72 x 1876100 (1876.1 s), ~1.01 GiB, data loaded>

In [13]:
raw_resampled.save(raw_resampled_fname, overwrite=True)

Overwriting existing file.
Writing E:\new_fieldline\sub-H\20260604_162421_sub-H_file-subjectHData_raw.fif
Overwriting existing file.
Closing E:\new_fieldline\sub-H\20260604_162421_sub-H_file-subjectHData_raw.fif
[done]


[WindowsPath('E:/new_fieldline/sub-H/20260604_162421_sub-H_file-subjectHData_raw.fif')]

In [14]:
print(raw_resampled.info)

<Info | 17 non-empty values
 bads: []
 ch_names: L102_bz-s30, L104_bz-s83, L106_bz-s81, L108_bz-s79, L110_bz-s70, ...
 chs: 71 Magnetometers, 1 Stimulus
 custom_ref_applied: False
 description: {"chassis":{"version":"0.9.4- ...
 dig: 6 items (3 Cardinal, 3 HPI)
 experimenter: KP
 file_id: 4 items (dict)
 gantry_angle: 0.0
 highpass: 0.1 Hz
 line_freq: 50.0
 lowpass: 250.0 Hz
 meas_date: 2026-06-04 15:24:21 UTC
 meas_id: 4 items (dict)
 nchan: 72
 proj_id: 21923
 proj_name: SFLUX
 projs: []
 sfreq: 1000.0 Hz
 xplotter_layout: None
>


Note that the sampling frequency is  sfreq = 1000 Hz. This is appropiate for more purposes. However, the data were to be resampled this would be the place to do it. 

## Converting to MEG BIDS format

The next step is to organize the FIF-data according to the BIDS convention. This includes identifying and naming the trigger information. 

In [15]:
del raw, raw_resampled
raw = mne.io.read_raw(raw_resampled_fname)

Opening raw data file E:/new_fieldline/sub-H\20260604_162421_sub-H_file-subjectHData_raw.fif...
    Range : 0 ... 1876099 =      0.000 ...  1876.099 secs
Ready.


### Identifying triggers and write a FIF file

The BIDS data will eventually include the trigger information. The next step is to identify the information in the trigger channels code in the FIF-file. This happens to be from trigger channel di32. The identified events are stored in an additional FIF-file in the BIDS. 

In [16]:
events = mne.find_events(raw, stim_channel="di32")
mne.write_events(event_fname, events, overwrite=True)

Finding events on: di32
Trigger channel di32 has a non-zero initial value of 1024 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
1399 events found on stim channel di32
Event IDs: [    4   256  1024  4096 16384 65536]
Overwriting existing file.
Overwriting existing file.


Print the first 10 events for verification

In [17]:
print(events[:10])  

[[104224      0    256]
 [105449      0   1024]
 [106208      0  16384]
 [106754      0      4]
 [107900      0   4096]
 [109150      0   1024]
 [109625      0  65536]
 [110108      0      4]
 [110111      0      4]
 [111559      0   4096]]


Line 3 of this output demonstrates that at sample-point 115734 there is a trigger with code 500. Subsequently, the trigger code from the channel di32 will be assigned labels. This will be dependent on the specific study-design and it is advisable to use informative labels

In [18]:
event_dict = {
    'cueRight': 256,       # Start of attention orientation
    'cueLeft': 4096,        # Start of attention orientation
    'stimOnset': 1024,      # Onset of moving gratings - end of attention orientation   # Onset of catch trial
    'dotOnRight': 16384,
    'dotOnLeft': 65536,
    'resp': 4,           # Button press

}

In this example, trigger value 200 denotes the onset of a trial and is therefore labeled 'trial_start'. Likewise 'cue_Right' (trigger 1) and 'cue_Left' (trigger 2) denote respective the displayed cues instructing the participants to attend left or right. 

### Organizing and storing the data according to BIDS

For the BIDS conversion, several parameters must be defined according to the subject and session number. 

In [19]:
raw.info["line_freq"] = 50
raw.set_annotations(None)
subject = '01'
session = '01'
task = 'SpAtt'
run = '01'

bids_path = BIDSPath(
    subject=subject, 
    session=session, 
    task=task, 
    run=run, 
    datatype="meg", 
    root=bids_folder
)
write_raw_bids(
    raw=raw,
    bids_path=bids_path,
    events=event_fname,
    event_id=event_dict,
    overwrite=True,
    allow_preload=True, 
    format='FIF',
    anonymize={'daysback': 5000, 'keep_his': False, 'keep_source': False}
)

Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\participants.tsv'...
Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\participants.json'...
Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\sub-01\ses-01\meg\sub-01_ses-01_coordsystem.json'...
Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\sub-01\ses-01\meg\sub-01_ses-01_coordsystem.json'...
Used Annotations descriptions: [np.str_('cueLeft'), np.str_('cueRight'), np.str_('dotOnLeft'), np.str_('dotOnRight'), np.str_('resp'), np.str_('stimOnset')]
Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\sub-01\ses-01\meg\sub-01_ses-01_task-SpAtt_run-01_events.tsv'...
Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\sub-01\ses-01\meg\sub-01_ses-01_task-SpAtt_run-01_events.json'...
Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\dataset_description.json'...
Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\sub-01\ses-01\meg\sub-01_ses-01_task-SpAtt_run-01_meg.json'...
Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt

C:\Users\arakshit\AppData\Local\Temp\ipykernel_37968\1009697983.py:16: RuntimeWarning: `daysback` is too small; the measurement date is after 1925, which is not recommended by BIDS.The minimum `daysback` value for changing the measurement date of this data to before this date is 37045
  write_raw_bids(


Writing E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\sub-01\ses-01\meg\sub-01_ses-01_task-SpAtt_run-01_meg.fif
Closing E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\sub-01\ses-01\meg\sub-01_ses-01_task-SpAtt_run-01_meg.fif
[done]
Writing 'E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\sub-01\ses-01\sub-01_ses-01_scans.tsv'...
Wrote E:\new_fieldline\sub-H\Fieldline_Spatt_BIDS\sub-01\ses-01\sub-01_ses-01_scans.tsv entry with meg\sub-01_ses-01_task-SpAtt_run-01_meg.fif.


BIDSPath(
root: E:/new_fieldline/sub-H/Fieldline_Spatt_BIDS
datatype: meg
basename: sub-01_ses-01_task-SpAtt_run-01_meg.fif)

To explore the data organization according to BIDS inspect the folders: 

In [20]:
print_dir_tree(bids_folder)

|Fieldline_Spatt_BIDS\
|--- README
|--- dataset_description.json
|--- participants.json
|--- participants.tsv
|--- derivatives\
|------ analysis\
|--------- sub-01\
|------------ ses-01\
|--------------- meg\
|------------------ sub-01_ses-01_task-SpAtt_run-01_epo.fif
|------ preprocessing\
|--------- sub-01\
|------------ ses-01\
|--------------- meg\
|------------------ sub-01_ses-01_task-SpAtt_run-01_split-01_ann-1.fif
|------------------ sub-01_ses-01_task-SpAtt_run-01_split-01_ann.csv
|------------------ sub-01_ses-01_task-SpAtt_run-01_split-01_ann.fif
|------------------ sub-01_ses-01_task-SpAtt_run-01_split-01_ica_raw-1.fif
|------------------ sub-01_ses-01_task-SpAtt_run-01_split-01_ica_raw.fif
|------------------ sub-01_ses-01_task-SpAtt_run-01_split-01_raw_hfc-1.fif
|------------------ sub-01_ses-01_task-SpAtt_run-01_split-01_raw_hfc.fif
|--- sub-01\
|------ ses-01\
|--------- sub-01_ses-01_scans.tsv
|--------- meg\
|------------ sub-01_ses-01_coordsystem.json
|------------ s

Some of these files are useful for inspecting the data. For instance, 'sub-01_ses-01_task-SpAtt_run-01_events.tsv' is a text-file storing the events and the associated labels. I can be inspected using any text editor. 

**Question 1:**   Inspect the file 'sub-01_ses-01_task-SpAtt_run-01_events.tsv' and report the time and sample points for the first occurrences of the 'cue_Left' and 'cue_Right' trigger, respectively.

## Preregistration and publication


Publication, example:

"The FIF-data sampled at 1000 Hz were organized according to MEG-BIDS convention [1]."



## References

[1] Niso G, Gorgolewski KJ, Bock E, Brooks TL, Flandin G, Gramfort A, Henson RN, Jas M, Litvak V, Moreau JT, Oostenveld R, Schoffelen JM, Tadel F, Wexler J, Baillet S. MEG-BIDS, the brain imaging data structure extended to magnetoencephalography. *Scientific Data* 5, 180110 (2018). [doi:10.1038/sdata.2018.110](https://doi.org/10.1038/sdata.2018.110).

[2] Smith SW. *The Scientist and Engineer's Guide to Digital Signal Processing*. California Technical Publishing, 1998. [PDF](https://www.dspguide.com/pdfbook.htm).
